version: '3'

services:
  bot:
    build: .
    container_name: telegram-download-bot
    volumes:
      - ./config:/app/config
      - ./downloads:/app/downloads
      - ./temp:/app/temp
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai 